config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#welcome'
  resources :users, :only => [:new, :create, :index, :update]
  get '/users/edit' => 'users#edit', :as => 'edit_user'

  post "/highscores" => "highscores#create"
  get "/highscores" => "highscores#index"
  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/highscore.rb
# == Schema Information
#
# Table name: highscores
#
#  id         :integer          not null, primary key
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Highscore < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_one :highscore
  has_secure_password
  validates :username, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user
  before_action :set_all_highscores

 
  private
  def set_all_highscores
    highscores = Highscore.all
    @allhighscores = Highscore.order(score: :desc).limit(5)
    # @topuser
  end
  def fetch_user
   @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
   gon.user_id = @current_user.id if @current_user
   session[:user_id] = nil unless @current_user.present?
  end
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  def new
    @highscore = Highscore.new
  end


  def create
  # @highscore = Highscore.new(highscore_params)
  @highscore = Highscore.find_by :user_id => params[:highscore][:user_id]
  if @highscore.nil?
    @highscore = Highscore.new(highscore_params)
  else
    @highscore.update( highscore_params ) if @highscore.score < params[:highscore][:score].to_i
  end

  respond_to do |format|
    if @highscore.save
      format.html { redirect_to @highscore, notice: 'Highscore was successfully created.' }
      format.json { render json: { status: "OK", score: @highscore.score } }
    else
      format.html { render :new }
      format.json { render json: @highscore.errors, status: :unprocessable_entity }
    end
   end
  end

  def show
  end

  def index
  # @allhighscores = Highscore.all

 # @allhighscores = Highscore.order(score: :desc).limit(5)

  end

  private
  def highscore_params
    params.require(:highscore).permit(:score, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
   user = User.find_by :username => params[:username]
     if user.present? && user.authenticate(params[:password])
       session[:user_id] = user.id
       #log em in
       redirect_to root_path
     else
       flash[:error] = "Oops"
       redirect_to login_path
   end
  end

  def destroy
   session[:user_id] = nil
   redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authorise, :only => [:index]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
  if @user.save
    redirect_to root_path
  else
    render :new
  end
  end

  def edit
  @user = @current_user
  end

  def update
    user = @current_user
    user.update user_params
    redirect_to root_path
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def authorise
  redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/highscores/index.html.erb
<!--
<div class="scorebox">
<h2>HIGHSCORES</h2>
<% @allhighscores.each do |scorelist| %>
<div class="scorelist">
<%if scorelist.user.present? %>
<p>
  User:
<%= scorelist.user.username%>
  =>
  Score:
<%= scorelist.score %>
</p>
</div>
<% end %>
<% end %>
</div> -->

app/views/highscores/new.html.erb
<h1>Highscores#new</h1>
<p>Find me in app/views/highscores/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aunidgame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= include_gon %>
  <%= Gon::Base.render_data %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

  <nav>
    <%= link_to 'Home', root_path %>
    <!-- <%= link_to 'Leaderboard', highscores_path %> -->
    <% if @current_user.present? %>
     <% if @current_user.admin? %>
     <%= link_to 'All Users', users_path %>
    <% end %>
                <%= link_to "Logout #{@current_user.username}", login_path, :method => :delete %>
                <%= link_to "Edit Profile", edit_user_path(@current_user) %>
              <% else %>
                <%= link_to "Sign up", signup_path %>
                <%= link_to "Login", login_path %>
              <% end %>
       </nav>

  <% if flash[:error].present? %>
  <h2> class="error"
   <%= flash[:error] %>
  </h2>
  <% end %>



<%= yield %>
 <div id="aunid"></div>
<div class="userscore">
  <h2 >YOUR HIGHSCORE</h2>
  <p id="highscore" class="scorelist">0</p>
</div>

<div class="scorebox">
<h2>HIGHSCORES</h2>
<% @allhighscores.each_with_index do |scorelist, index| %>
<div class="scorelist">


<p>
  <% if index == 0  %>
  <%= image_tag "crown.png" %>
<% end %>
<% if index == 1  %>
<%= image_tag "silvercrown.png" %>
<% end %>
<% if index == 2  %>
<%= image_tag "bronzecrown.png" %>
<% end %>

  User:
<%= scorelist.user.username if scorelist.user %>
   =>
  Score:
<%= scorelist.score if scorelist.score%>

<% if index == 0  %>
<%= image_tag "crown.png" %>
<% end %>
<% if index == 1  %>
<%= image_tag "silvercrown.png" %>
<% end %>
<% if index == 2  %>
<%= image_tag "bronzecrown.png" %>
<% end %>

</p>
</div>
<% end %>
</div>


</div>
</body>
</html>

app/views/pages/welcome.html.erb
<!-- <div class="userscore">
  <h2 >Current Highscore:</h2>
  <h2 id="highscore">0</h2>
</div> -->

app/views/session/new.html.erb
<h1>Login</h1>

<%= form_tag login_path do %>
  <%= label_tag :username %>
  <%= text_field_tag :username %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag %>
<% end %>

app/views/users/edit.html.erb
<h1>EDIT USER</h1>
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.label :image%>
<%= f.url_field :image %>

<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>ALL USERS TOP SECRET</h1>
<% @users.each do |user| %>
<p>
  <%= user.username %> since <%= user.created_at %>
</p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
<ol>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%=  msg %></li>
  <% end %>
</ol>
<% end %>


          <%= form_for @user do |f| %>

            <%= f.label :username %>
            <%= f.text_field :username, :required => true %>

            <%= f.label :password %>
            <%= f.password_field :password, :required => true %>

            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, :required => true %>
            <%= f.submit "signup" %>
          <% end %>